name = "cloudflare-agent-worker"
main = "src/index.ts"
compatibility_date = "2024-03-30"

[vars]
WORKER_NAME = "cloudflare-agent-worker"

[[d1_databases]]
binding = "D1"
database_name = "assistant_prompts"
database_id = "00000000-0000-0000-0000-000000000000"

[[kv_namespaces]]
binding = "KV_CACHE"
id = "11111111111111111111111111111111"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "repo-artifacts"

[ai]
binding = "AI"
