repositories:
  - name: awesome-assistants
    url: https://github.com/awesome-assistants/awesome-assistants
    branch: main
    enabled: true
    sync_strategy: incremental
    check_interval_cron: "0 */6 * * *"  # Every 6 hours
    files_to_sync:
      - source: assistants.yaml
        destination: synced-data/awesome-assistants/assistants.yaml
    post_sync_actions:
      - type: python_script
        script: scripts/sync/process_assistants.py
        args:
          - --file
          - synced-data/awesome-assistants/assistants.yaml
          - --cloudflare-endpoint
          - ${CLOUDFLARE_WORKER_URL}/assistants
