name = "best-hits-api"
main = "../frontend/dist/_worker.js/index.js"
compatibility_date = "2024-03-30"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "best-hits"
database_id = "91345eec-1835-4a1a-9215-ca02a1fb7742"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "KV_CACHE"
id = "cdf97035ffa74a029adad17636179c81"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "best-hits"

[ai]
binding = "AI"

[assets]
directory = "../frontend/dist"
binding = "ASSETS"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

# WORKER_API_KEY already setup as a secret on the worker
